apiVersion: v1
kind: Service
metadata:
  name: timestamp-db-service
spec:
  type: NodePort
  selector:
    app: timestamp-db
  ports:
    - name: "timestamp"
      protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 21433