apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 8888