apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-db
  template:
    metadata:
      labels:
        app: timestamp-db
    spec:
      containers:
        - name: timestamp-db
          image: hemanthtestacr.azurecr.io/timestamprepo/postgres:13-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: timestamp-db-config

---
apiVersion: v1
kind: Service
metadata:
  name: timestamp-db
  labels:
    app: timestamp-db
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: timestamp-db